Repository gtk-rs/gtk-rs-core, pull requests merged in 2022-10, with the labels that each got.

#795 pangocairo: Trust upstream nullable annotations for return values
  pangocairo/Gir.toml
  pangocairo/src/auto/font_map.rs
  pangocairo/src/auto/functions.rs
  pangocairo/tests/iterators.rs
Labels: pango

#801 glib: Add a getter for `ObjectBuilder::type_`
  glib/src/object.rs
Labels: needs-backport

#802 glib: Add helpers for setting property bindings flags
  glib/src/gobject/binding.rs
  glib/src/gobject/binding_group.rs
  glib/src/object.rs
Labels: needs-backport

#803 cairo: Fix rectangle getter
  cairo/src/rectangle.rs
Labels: needs-backport

#806 glib: Add `ObjectSubclass::obj()` as a shorter alias for `instance()`
  glib/src/subclass/types.rs
Labels: needs-backport

#809 gio: Add helpers for setting SettingBinding flags
  gio/src/settings.rs
  glib/src/gobject/binding_group.rs
  glib/src/object.rs
Labels: gio, needs-backport

#810 gio: Add set_only/get_only helpers to BindingBuilder
  gio/src/settings.rs
Labels: gio, needs-backport

#811 glib: Add unsafe bindings to `g_object_run_dispose()`
  glib/src/object.rs
Labels: needs-backport
