Repository gtk-rs/gtk-rs-core, pull requests merged in 2023-02, with the labels that each got.

#974 param_spec: add ParamSpecEnumBuilder::default_value()
  glib/src/param_spec.rs
Labels: needs-backport

#977 glib: Add various `IntoStrV` impls
  glib/src/collections/strv.rs
Labels: needs-backport

#979 Implement Default trait for vectors
  graphene/src/box_.rs
  graphene/src/matrix.rs
  graphene/src/point.rs
  graphene/src/point3_d.rs
  graphene/src/rect.rs
  graphene/src/vec2.rs
  graphene/src/vec3.rs
  graphene/src/vec4.rs
Labels: needs-backport

#995 properties: impl HasParamSpec for Vec<String> and StrV
  glib-macros/tests/properties.rs
  glib/src/param_spec.rs
Labels: needs-backport

#994 glib-macros: slightly improve Properties macro docs
  glib-macros/src/lib.rs
Labels: needs-backport

#999 Derive HasParamSpec for SharedBoxed
  glib-macros/src/shared_boxed_derive.rs
Labels: needs-backport

#1003 glib: add missing ObjectImpl vfuncs overrides
  glib/src/subclass/object.rs
Labels: glib, needs-backport

#1015 gio: Don't pass `NULL` to `g_list_store_find_with_equal_func_full()`
  gio/src/list_store.rs
Labels: needs-backport

#1016 glib: Optimize `IntoGStr` impl for `String` by simply appending a NUL-byte
  glib/src/gstring.rs
Labels: needs-backport

#1017 glib: implement WatchedObject for BorrowedObject
  glib-macros/tests/test.rs
  glib/src/object.rs
Labels: needs-backport

#1027 glib: Add connect_notify* methods to SignalGroup
  glib/src/gobject/signal_group.rs
Labels: needs-backport

#1031 pangocairo-sys: fix package.description in Cargo.toml
  pangocairo/sys/Cargo.toml
Labels: needs-backport

#1023 Add nullable attribute on properties macro
  glib-macros/src/lib.rs
  glib-macros/src/properties.rs
  glib-macros/tests/properties.rs
Labels: glib-macros, needs-backport

#1000 Add ValueDelegate macro
  glib-macros/src/lib.rs
  glib-macros/src/value_delegate_derive.rs
  glib-macros/tests/properties.rs
  glib/src/lib.rs
Labels: enhancement, needs-backport
